version: "3"
services:
  toogoodtogo-watcher:
    image: marklagendijk/toogoodtogo-watcher:3.9.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/home/node/.config/toogoodtogo-watcher-nodejs