version: "3"
services:
  litestream_db:
    image: litestream/litestream:0.3.8
    restart: always
    volumes:
      - ./litestream.yml:/etc/litestream.yml
      - litestream_db:/db
    entrypoint: /usr/local/bin/litestream replicate

  web_recipes:
    image: vabene1111/recipes:1.1.4
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - mediafiles:/opt/recipes/mediafiles
      - litestream_db:/opt/recipes/db
      - ./files/:/opt/recipes/import/
    depends_on:
      - litestream_db
    networks:
      - default

  nginx_recipes:
    image: nginx:1.21-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - mediafiles:/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.rule=Host(`rezepte.${BASE_DOMAIN}`) || Host(`rezepte.${BASE_PERSONAL_DOMAIN}`)"
      - "traefik.http.middlewares.xframe.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.routers.recipes.middlewares=xframe@docker"
      - "traefik.http.routers.recipes.tls.certresolver=ncresolver"
    depends_on:
      - web_recipes
    networks:
      - default
      - traefik

    
  backup-rclone:
    image: offen/docker-volume-backup:v2.15.0
    restart: always
    env_file: ./backup.env
    volumes:
      - ./notifications.tmpl:/etc/dockervolumebackup/notifications.d/notifications.tmpl
      - mediafiles:/backup/tandoor-mediafiles-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - rclone_azure_volume:/archive


networks:
  default: null
  traefik:
    external: true

volumes:
  nginx_config:
    driver: local
  staticfiles:
    driver: local
  litestream_db:
    driver: local
  mediafiles:
    driver: local
  rclone_azure_volume:
    # To use this install rclone plugin: 
    # rclone/docker-volume-rclone:amd64 --grant-all-permissions --alias rclone
    driver: rclone:latest
    driver_opts:
      type: azureblob
      path: $AZURE_BLOB_CONTAINER
      azureblob-account: $AZURE_BLOB_ACCOUNT
      azureblob-key: $AZURE_BLOB_KEY
      allow_other: 'true'
