version: '3.3'

services:
  traefik:
    image: traefik:v2.7.1
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - "./dynamic.yml:/dynamic.yml"
      - "./traefik.prod.yml:/etc/traefik/traefik.yml"
    environment:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
networks:
  default:
    external:
      name: traefik
