http:
  routers:
    avv-router:
      entryPoints:
        - "websecure"
      rule: "Host(`avv.{{env "BASE_DOMAIN"}}`) && PathPrefix(`/avv2/`)"
      tls:
        certResolver: ncresolver
      middlewares:
        - constructAVVRequest
      service: "avv-proxy@file"

    uptime-redirect-router:
      entryPoints:
        - "websecure"
      rule: "Host(`up.{{env "BASE_PERSONAL_DOMAIN"}}`) || Host(`up.{{env "BASE_DOMAIN"}}`)"
      middlewares:
        - redirect-uptime-monitor@file
      service: "uptime-redirect-noop-service@file"

    dashboard:
      entryPoints:
        - "websecure"
      rule: Host(`traefik.{{env "BASE_PERSONAL_DOMAIN"}}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls:
        certResolver: ncresolver
      middlewares:
        - dashboard_auth

  middlewares:
    redirect-uptime-monitor:
      redirectRegex:
        regex: "^https://up\\.({{env "BASE_PERSONAL_DOMAIN"}}|{{env "BASE_DOMAIN"}})"
        replacement: "https://gloriousdan.github.io/Homelab-uptime"

    constructAVVRequest:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Origin: "*"
          Content-Type: "text/html; charset=UTF-8"

    dashboard_auth:
      basicAuth:
        users:
          - {{env "DASHBOARD_USER"}}

  services:
    avv-proxy:
      loadBalancer:
        servers:
          - url: https://efa.avv-augsburg.de

    uptime-redirect-noop-service:
      loadBalancer:
        servers:
          # This service is never hit with a request
          - url: ""  