http:
  routers:
    avv-router:
      entryPoints:
        - "websecure"
      rule: "Host(`avv.{{env "BASE_DOMAIN"}}`) && PathPrefix(`/avv2/`)"
      tls:
        certResolver: ncresolver
      middlewares:
        - constructAVVRequest
      service: "avv-proxy@file"

    dashboard:
      entryPoints:
        - "websecure"
      rule: Host(`traefik.{{env "BASE_PERSONAL_DOMAIN"}}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      tls:
        certResolver: ncresolver
      middlewares:
        - dashboard_auth

  middlewares:
    constructAVVRequest:
      headers:
        customResponseHeaders:
          Access-Control-Allow-Origin: "*"
          Content-Type: "text/html; charset=UTF-8"

    dashboard_auth:
      basicAuth:
        users:
          - {{env "DASHBOARD_USER"}}

  services:
    avv-proxy:
      loadBalancer:
        servers:
          - url: https://efa.avv-augsburg.de
