version: '3.3'

services:
  static:
    image: nginx:1.23-alpine

    container_name: static-files
    restart: unless-stopped
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.static-files.rule=Host(`avv.${BASE_DOMAIN}`)
      - traefik.http.routers.static-files.tls=true
      - traefik.http.routers.static-files.tls.certresolver=ncresolver
      - traefik.http.services.static-files.loadbalancer.server.port=80
      - "traefik.http.middlewares.static-files-replacepath.replacepath.path=/"

      - "traefik.http.routers.static-files.middlewares=static-files-replacepath@docker"
    volumes:
      - ./files:/usr/share/nginx/html:ro

networks:
  default:
    external:
      name: traefik
